### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by DuchGhast** [Kotlin/kotlinx-io#116]

**Comment by altavir** [comment]
No, it is not. The active development will continue after there some free people to work on it. For now, you can join the discussion at kotlin slack #io channel.

**Comment by qwwdfsad** [comment]
It's not dead, but indeed we lack of engineering resource to make a fully-paced development with thoughtful design and meticulous implementation.

**Comment by soberich** [comment]
@altavir @qwwdfsad is it possible to set a release from current master with whatever you guys/Jetbrains prefer? Jitpack, github actions, etc.?

**Comment by altavir** [comment]
@soberich It is not dead, it is put on hold until someone has manpower to properly work on it.  For now, you can use [my fork](https://bintray.com/beta/#/mipt-npm/dev/kotlinx-io/0.2.0-npm-dev-11?tab=overview), but sadly I can't fully maintain it because of problems with native deployment (I do not think it is possible to properly deploy it without proper continuous integration infrastructure. Ktor-io covers basic uses, but I agree that its design is not the most transparent.

**Comment by jnorthrup** [comment]
![image](https://user-images.githubusercontent.com/73514/122688640-0a7b4700-d250-11eb-82bf-77d1a5ccdab0.png)

**Comment by DaRacci** [comment]
Well its officially dead now

**Comment by qwwdfsad** [comment]
The status is reflected in readme for now
