### ISSUE TITLE
Support more native targets

### ISSUE THREAD

**Issue by Dominaezzz** [Kotlin/kotlinx-io#45]
I'm mostly thinking of `androidNativeArm64`, `androidNativeArm32` and `wasm` but you might as well just publish for all them.

I want to get a Vulkan sample working on native android and I use this library for `IoBuffer` (until `Memory` is released).

Is there anything blocking the support of other targets?

**Comment by Dominaezzz** [comment]
Also, `androidNativeX86` and `androidNativeX64`. Would a PR for this be accepted?

**Comment by qwwdfsad** [comment]
Thanks for letting us know.
Unfortunately, we are not ready to accept PR yet. The problem is not Gradle configuration, but everything else -- setting up a test environment, building a publciation pipeline that supports these targets etc.
We are going to add these platforms (except `wasm` that libraries don't support in general) after the initial experimental release
